#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="smsdb")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void Insertwall_task_erro_info(wall_task_erro_info instance);
  partial void Updatewall_task_erro_info(wall_task_erro_info instance);
  partial void Deletewall_task_erro_info(wall_task_erro_info instance);
  partial void Insertwall_task_running_info(wall_task_running_info instance);
  partial void Updatewall_task_running_info(wall_task_running_info instance);
  partial void Deletewall_task_running_info(wall_task_running_info instance);
  partial void Insertbeibo(beibo instance);
  partial void Updatebeibo(beibo instance);
  partial void Deletebeibo(beibo instance);
  partial void Insertwall_complete_task(wall_complete_task instance);
  partial void Updatewall_complete_task(wall_complete_task instance);
  partial void Deletewall_complete_task(wall_complete_task instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["smsdbConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<wall_task_erro_info> wall_task_erro_info
	{
		get
		{
			return this.GetTable<wall_task_erro_info>();
		}
	}
	
	public System.Data.Linq.Table<wall_task_running_info> wall_task_running_info
	{
		get
		{
			return this.GetTable<wall_task_running_info>();
		}
	}
	
	public System.Data.Linq.Table<beibo> beibo
	{
		get
		{
			return this.GetTable<beibo>();
		}
	}
	
	public System.Data.Linq.Table<wall_complete_task> wall_complete_task
	{
		get
		{
			return this.GetTable<wall_complete_task>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.wall_task_erro_info")]
public partial class wall_task_erro_info : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _task_guid;
	
	private string _task_name;
	
	private int _status;
	
	private string _task_type;
	
	private string _description;
	
	private System.DateTime _createtime;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontask_guidChanging(System.Guid value);
    partial void Ontask_guidChanged();
    partial void Ontask_nameChanging(string value);
    partial void Ontask_nameChanged();
    partial void OnstatusChanging(int value);
    partial void OnstatusChanged();
    partial void Ontask_typeChanging(string value);
    partial void Ontask_typeChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OncreatetimeChanging(System.DateTime value);
    partial void OncreatetimeChanged();
    #endregion
	
	public wall_task_erro_info()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_task_guid", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid task_guid
	{
		get
		{
			return this._task_guid;
		}
		set
		{
			if ((this._task_guid != value))
			{
				this.Ontask_guidChanging(value);
				this.SendPropertyChanging();
				this._task_guid = value;
				this.SendPropertyChanged("task_guid");
				this.Ontask_guidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_task_name", DbType="Char(512) NOT NULL", CanBeNull=false)]
	public string task_name
	{
		get
		{
			return this._task_name;
		}
		set
		{
			if ((this._task_name != value))
			{
				this.Ontask_nameChanging(value);
				this.SendPropertyChanging();
				this._task_name = value;
				this.SendPropertyChanged("task_name");
				this.Ontask_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int NOT NULL")]
	public int status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_task_type", DbType="Char(32)")]
	public string task_type
	{
		get
		{
			return this._task_type;
		}
		set
		{
			if ((this._task_type != value))
			{
				this.Ontask_typeChanging(value);
				this.SendPropertyChanging();
				this._task_type = value;
				this.SendPropertyChanged("task_type");
				this.Ontask_typeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="Char(128)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createtime", DbType="DateTime NOT NULL")]
	public System.DateTime createtime
	{
		get
		{
			return this._createtime;
		}
		set
		{
			if ((this._createtime != value))
			{
				this.OncreatetimeChanging(value);
				this.SendPropertyChanging();
				this._createtime = value;
				this.SendPropertyChanged("createtime");
				this.OncreatetimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.wall_task_running_info")]
public partial class wall_task_running_info : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _task_guid;
	
	private string _task_name;
	
	private int _status;
	
	private string _task_type;
	
	private string _description;
	
	private System.DateTime _createtime;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontask_guidChanging(System.Guid value);
    partial void Ontask_guidChanged();
    partial void Ontask_nameChanging(string value);
    partial void Ontask_nameChanged();
    partial void OnstatusChanging(int value);
    partial void OnstatusChanged();
    partial void Ontask_typeChanging(string value);
    partial void Ontask_typeChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OncreatetimeChanging(System.DateTime value);
    partial void OncreatetimeChanged();
    #endregion
	
	public wall_task_running_info()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_task_guid", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid task_guid
	{
		get
		{
			return this._task_guid;
		}
		set
		{
			if ((this._task_guid != value))
			{
				this.Ontask_guidChanging(value);
				this.SendPropertyChanging();
				this._task_guid = value;
				this.SendPropertyChanged("task_guid");
				this.Ontask_guidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_task_name", DbType="Char(512) NOT NULL", CanBeNull=false)]
	public string task_name
	{
		get
		{
			return this._task_name;
		}
		set
		{
			if ((this._task_name != value))
			{
				this.Ontask_nameChanging(value);
				this.SendPropertyChanging();
				this._task_name = value;
				this.SendPropertyChanged("task_name");
				this.Ontask_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int NOT NULL")]
	public int status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_task_type", DbType="Char(32) NOT NULL", CanBeNull=false)]
	public string task_type
	{
		get
		{
			return this._task_type;
		}
		set
		{
			if ((this._task_type != value))
			{
				this.Ontask_typeChanging(value);
				this.SendPropertyChanging();
				this._task_type = value;
				this.SendPropertyChanged("task_type");
				this.Ontask_typeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="Char(128)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createtime", DbType="DateTime NOT NULL")]
	public System.DateTime createtime
	{
		get
		{
			return this._createtime;
		}
		set
		{
			if ((this._createtime != value))
			{
				this.OncreatetimeChanging(value);
				this.SendPropertyChanging();
				this._createtime = value;
				this.SendPropertyChanged("createtime");
				this.OncreatetimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.beibo")]
public partial class beibo : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _beibo_count;
	
	private int _type;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbeibo_countChanging(int value);
    partial void Onbeibo_countChanged();
    partial void OntypeChanging(int value);
    partial void OntypeChanged();
    #endregion
	
	public beibo()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beibo_count", DbType="Int NOT NULL")]
	public int beibo_count
	{
		get
		{
			return this._beibo_count;
		}
		set
		{
			if ((this._beibo_count != value))
			{
				this.Onbeibo_countChanging(value);
				this.SendPropertyChanging();
				this._beibo_count = value;
				this.SendPropertyChanged("beibo_count");
				this.Onbeibo_countChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int type
	{
		get
		{
			return this._type;
		}
		set
		{
			if ((this._type != value))
			{
				this.OntypeChanging(value);
				this.SendPropertyChanging();
				this._type = value;
				this.SendPropertyChanged("type");
				this.OntypeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.wall_complete_task")]
public partial class wall_complete_task : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _task_type;
	
	private int _count;
	
	private string _Memo;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontask_typeChanging(int value);
    partial void Ontask_typeChanged();
    partial void OncountChanging(int value);
    partial void OncountChanged();
    partial void OnMemoChanging(string value);
    partial void OnMemoChanged();
    #endregion
	
	public wall_complete_task()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_task_type", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int task_type
	{
		get
		{
			return this._task_type;
		}
		set
		{
			if ((this._task_type != value))
			{
				this.Ontask_typeChanging(value);
				this.SendPropertyChanging();
				this._task_type = value;
				this.SendPropertyChanged("task_type");
				this.Ontask_typeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_count", DbType="Int NOT NULL")]
	public int count
	{
		get
		{
			return this._count;
		}
		set
		{
			if ((this._count != value))
			{
				this.OncountChanging(value);
				this.SendPropertyChanging();
				this._count = value;
				this.SendPropertyChanged("count");
				this.OncountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Memo", DbType="NChar(100)")]
	public string Memo
	{
		get
		{
			return this._Memo;
		}
		set
		{
			if ((this._Memo != value))
			{
				this.OnMemoChanging(value);
				this.SendPropertyChanging();
				this._Memo = value;
				this.SendPropertyChanged("Memo");
				this.OnMemoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
