#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WorkFlow")]
public partial class workDBDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void Insertworkhistory(workhistory instance);
  partial void Updateworkhistory(workhistory instance);
  partial void Deleteworkhistory(workhistory instance);
  partial void Insertworker(worker instance);
  partial void Updateworker(worker instance);
  partial void Deleteworker(worker instance);
  partial void Insertpermission(permission instance);
  partial void Updatepermission(permission instance);
  partial void Deletepermission(permission instance);
  partial void Insertovertime(overtime instance);
  partial void Updateovertime(overtime instance);
  partial void Deleteovertime(overtime instance);
  partial void Insertworkoff(workoff instance);
  partial void Updateworkoff(workoff instance);
  partial void Deleteworkoff(workoff instance);
  #endregion
	
	public workDBDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WorkFlowConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public workDBDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public workDBDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public workDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public workDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<workhistory> workhistory
	{
		get
		{
			return this.GetTable<workhistory>();
		}
	}
	
	public System.Data.Linq.Table<worker> worker
	{
		get
		{
			return this.GetTable<worker>();
		}
	}
	
	public System.Data.Linq.Table<permission> permission
	{
		get
		{
			return this.GetTable<permission>();
		}
	}
	
	public System.Data.Linq.Table<overtime> overtime
	{
		get
		{
			return this.GetTable<overtime>();
		}
	}
	
	public System.Data.Linq.Table<workoff> workoff
	{
		get
		{
			return this.GetTable<workoff>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.workhistory")]
public partial class workhistory : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _worker;
	
	private string _worker1;
	
	private System.Nullable<System.DateTime> _worktime;
	
	private string _workcontent;
	
	private string _workcontent1;
	
	private string _workstatus;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnworkerChanging(string value);
    partial void OnworkerChanged();
    partial void Onworker1Changing(string value);
    partial void Onworker1Changed();
    partial void OnworktimeChanging(System.Nullable<System.DateTime> value);
    partial void OnworktimeChanged();
    partial void OnworkcontentChanging(string value);
    partial void OnworkcontentChanged();
    partial void Onworkcontent1Changing(string value);
    partial void Onworkcontent1Changed();
    partial void OnworkstatusChanging(string value);
    partial void OnworkstatusChanged();
    #endregion
	
	public workhistory()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_worker", DbType="VarChar(20)")]
	public string worker
	{
		get
		{
			return this._worker;
		}
		set
		{
			if ((this._worker != value))
			{
				this.OnworkerChanging(value);
				this.SendPropertyChanging();
				this._worker = value;
				this.SendPropertyChanged("worker");
				this.OnworkerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_worker1", DbType="VarChar(20)")]
	public string worker1
	{
		get
		{
			return this._worker1;
		}
		set
		{
			if ((this._worker1 != value))
			{
				this.Onworker1Changing(value);
				this.SendPropertyChanging();
				this._worker1 = value;
				this.SendPropertyChanged("worker1");
				this.Onworker1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_worktime", DbType="DateTime")]
	public System.Nullable<System.DateTime> worktime
	{
		get
		{
			return this._worktime;
		}
		set
		{
			if ((this._worktime != value))
			{
				this.OnworktimeChanging(value);
				this.SendPropertyChanging();
				this._worktime = value;
				this.SendPropertyChanged("worktime");
				this.OnworktimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workcontent", DbType="NVarChar(MAX)")]
	public string workcontent
	{
		get
		{
			return this._workcontent;
		}
		set
		{
			if ((this._workcontent != value))
			{
				this.OnworkcontentChanging(value);
				this.SendPropertyChanging();
				this._workcontent = value;
				this.SendPropertyChanged("workcontent");
				this.OnworkcontentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workcontent1", DbType="NVarChar(MAX)")]
	public string workcontent1
	{
		get
		{
			return this._workcontent1;
		}
		set
		{
			if ((this._workcontent1 != value))
			{
				this.Onworkcontent1Changing(value);
				this.SendPropertyChanging();
				this._workcontent1 = value;
				this.SendPropertyChanged("workcontent1");
				this.Onworkcontent1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workstatus", DbType="VarChar(1)")]
	public string workstatus
	{
		get
		{
			return this._workstatus;
		}
		set
		{
			if ((this._workstatus != value))
			{
				this.OnworkstatusChanging(value);
				this.SendPropertyChanging();
				this._workstatus = value;
				this.SendPropertyChanged("workstatus");
				this.OnworkstatusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.worker")]
public partial class worker : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _username;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    #endregion
	
	public worker()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(20)")]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this.OnusernameChanging(value);
				this.SendPropertyChanging();
				this._username = value;
				this.SendPropertyChanged("username");
				this.OnusernameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.permission")]
public partial class permission : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _username;
	
	private System.Nullable<int> _permission1;
	
	private string _userid;
	
	private string _pwd;
	
	private System.Nullable<double> _quotan;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void Onpermission1Changing(System.Nullable<int> value);
    partial void Onpermission1Changed();
    partial void OnuseridChanging(string value);
    partial void OnuseridChanged();
    partial void OnpwdChanging(string value);
    partial void OnpwdChanged();
    partial void OnquotanChanging(System.Nullable<double> value);
    partial void OnquotanChanged();
    #endregion
	
	public permission()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(20)")]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this.OnusernameChanging(value);
				this.SendPropertyChanging();
				this._username = value;
				this.SendPropertyChanged("username");
				this.OnusernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="permission", Storage="_permission1", DbType="Int")]
	public System.Nullable<int> permission1
	{
		get
		{
			return this._permission1;
		}
		set
		{
			if ((this._permission1 != value))
			{
				this.Onpermission1Changing(value);
				this.SendPropertyChanging();
				this._permission1 = value;
				this.SendPropertyChanged("permission1");
				this.Onpermission1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="VarChar(20)")]
	public string userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				this.OnuseridChanging(value);
				this.SendPropertyChanging();
				this._userid = value;
				this.SendPropertyChanged("userid");
				this.OnuseridChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd", DbType="VarChar(20)")]
	public string pwd
	{
		get
		{
			return this._pwd;
		}
		set
		{
			if ((this._pwd != value))
			{
				this.OnpwdChanging(value);
				this.SendPropertyChanging();
				this._pwd = value;
				this.SendPropertyChanged("pwd");
				this.OnpwdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quotan", DbType="Float")]
	public System.Nullable<double> quotan
	{
		get
		{
			return this._quotan;
		}
		set
		{
			if ((this._quotan != value))
			{
				this.OnquotanChanging(value);
				this.SendPropertyChanging();
				this._quotan = value;
				this.SendPropertyChanged("quotan");
				this.OnquotanChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.overtime")]
public partial class overtime : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _name;
	
	private System.Nullable<System.DateTime> _originwork;
	
	private System.Nullable<System.DateTime> _overwork;
	
	private string _origin_shift;
	
	private string _current_shift;
	
	private string _origin_week;
	
	private string _current_week;
	
	private string _reason;
	
	private System.Nullable<int> _approve;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnoriginworkChanging(System.Nullable<System.DateTime> value);
    partial void OnoriginworkChanged();
    partial void OnoverworkChanging(System.Nullable<System.DateTime> value);
    partial void OnoverworkChanged();
    partial void Onorigin_shiftChanging(string value);
    partial void Onorigin_shiftChanged();
    partial void Oncurrent_shiftChanging(string value);
    partial void Oncurrent_shiftChanged();
    partial void Onorigin_weekChanging(string value);
    partial void Onorigin_weekChanged();
    partial void Oncurrent_weekChanging(string value);
    partial void Oncurrent_weekChanged();
    partial void OnreasonChanging(string value);
    partial void OnreasonChanged();
    partial void OnapproveChanging(System.Nullable<int> value);
    partial void OnapproveChanged();
    #endregion
	
	public overtime()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(20)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_originwork", DbType="DateTime")]
	public System.Nullable<System.DateTime> originwork
	{
		get
		{
			return this._originwork;
		}
		set
		{
			if ((this._originwork != value))
			{
				this.OnoriginworkChanging(value);
				this.SendPropertyChanging();
				this._originwork = value;
				this.SendPropertyChanged("originwork");
				this.OnoriginworkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_overwork", DbType="DateTime")]
	public System.Nullable<System.DateTime> overwork
	{
		get
		{
			return this._overwork;
		}
		set
		{
			if ((this._overwork != value))
			{
				this.OnoverworkChanging(value);
				this.SendPropertyChanging();
				this._overwork = value;
				this.SendPropertyChanged("overwork");
				this.OnoverworkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_origin_shift", DbType="VarChar(20)")]
	public string origin_shift
	{
		get
		{
			return this._origin_shift;
		}
		set
		{
			if ((this._origin_shift != value))
			{
				this.Onorigin_shiftChanging(value);
				this.SendPropertyChanging();
				this._origin_shift = value;
				this.SendPropertyChanged("origin_shift");
				this.Onorigin_shiftChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_current_shift", DbType="VarChar(20)")]
	public string current_shift
	{
		get
		{
			return this._current_shift;
		}
		set
		{
			if ((this._current_shift != value))
			{
				this.Oncurrent_shiftChanging(value);
				this.SendPropertyChanging();
				this._current_shift = value;
				this.SendPropertyChanged("current_shift");
				this.Oncurrent_shiftChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_origin_week", DbType="VarChar(20)")]
	public string origin_week
	{
		get
		{
			return this._origin_week;
		}
		set
		{
			if ((this._origin_week != value))
			{
				this.Onorigin_weekChanging(value);
				this.SendPropertyChanging();
				this._origin_week = value;
				this.SendPropertyChanged("origin_week");
				this.Onorigin_weekChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_current_week", DbType="VarChar(20)")]
	public string current_week
	{
		get
		{
			return this._current_week;
		}
		set
		{
			if ((this._current_week != value))
			{
				this.Oncurrent_weekChanging(value);
				this.SendPropertyChanging();
				this._current_week = value;
				this.SendPropertyChanged("current_week");
				this.Oncurrent_weekChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reason", DbType="VarChar(100)")]
	public string reason
	{
		get
		{
			return this._reason;
		}
		set
		{
			if ((this._reason != value))
			{
				this.OnreasonChanging(value);
				this.SendPropertyChanging();
				this._reason = value;
				this.SendPropertyChanged("reason");
				this.OnreasonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_approve", DbType="Int")]
	public System.Nullable<int> approve
	{
		get
		{
			return this._approve;
		}
		set
		{
			if ((this._approve != value))
			{
				this.OnapproveChanging(value);
				this.SendPropertyChanging();
				this._approve = value;
				this.SendPropertyChanged("approve");
				this.OnapproveChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.workoff")]
public partial class workoff : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _name;
	
	private System.Nullable<System.DateTime> _starttime;
	
	private System.Nullable<System.DateTime> _endtime;
	
	private string _originshift;
	
	private string _currentshift;
	
	private string _originweek;
	
	private string _currentweek;
	
	private string _reason;
	
	private System.Nullable<int> _approve;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnstarttimeChanging(System.Nullable<System.DateTime> value);
    partial void OnstarttimeChanged();
    partial void OnendtimeChanging(System.Nullable<System.DateTime> value);
    partial void OnendtimeChanged();
    partial void OnoriginshiftChanging(string value);
    partial void OnoriginshiftChanged();
    partial void OncurrentshiftChanging(string value);
    partial void OncurrentshiftChanged();
    partial void OnoriginweekChanging(string value);
    partial void OnoriginweekChanged();
    partial void OncurrentweekChanging(string value);
    partial void OncurrentweekChanged();
    partial void OnreasonChanging(string value);
    partial void OnreasonChanged();
    partial void OnapproveChanging(System.Nullable<int> value);
    partial void OnapproveChanged();
    #endregion
	
	public workoff()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(20)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_starttime", DbType="DateTime")]
	public System.Nullable<System.DateTime> starttime
	{
		get
		{
			return this._starttime;
		}
		set
		{
			if ((this._starttime != value))
			{
				this.OnstarttimeChanging(value);
				this.SendPropertyChanging();
				this._starttime = value;
				this.SendPropertyChanged("starttime");
				this.OnstarttimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endtime", DbType="DateTime")]
	public System.Nullable<System.DateTime> endtime
	{
		get
		{
			return this._endtime;
		}
		set
		{
			if ((this._endtime != value))
			{
				this.OnendtimeChanging(value);
				this.SendPropertyChanging();
				this._endtime = value;
				this.SendPropertyChanged("endtime");
				this.OnendtimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_originshift", DbType="VarChar(20)")]
	public string originshift
	{
		get
		{
			return this._originshift;
		}
		set
		{
			if ((this._originshift != value))
			{
				this.OnoriginshiftChanging(value);
				this.SendPropertyChanging();
				this._originshift = value;
				this.SendPropertyChanged("originshift");
				this.OnoriginshiftChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currentshift", DbType="VarChar(20)")]
	public string currentshift
	{
		get
		{
			return this._currentshift;
		}
		set
		{
			if ((this._currentshift != value))
			{
				this.OncurrentshiftChanging(value);
				this.SendPropertyChanging();
				this._currentshift = value;
				this.SendPropertyChanged("currentshift");
				this.OncurrentshiftChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_originweek", DbType="VarChar(20)")]
	public string originweek
	{
		get
		{
			return this._originweek;
		}
		set
		{
			if ((this._originweek != value))
			{
				this.OnoriginweekChanging(value);
				this.SendPropertyChanging();
				this._originweek = value;
				this.SendPropertyChanged("originweek");
				this.OnoriginweekChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currentweek", DbType="VarChar(20)")]
	public string currentweek
	{
		get
		{
			return this._currentweek;
		}
		set
		{
			if ((this._currentweek != value))
			{
				this.OncurrentweekChanging(value);
				this.SendPropertyChanging();
				this._currentweek = value;
				this.SendPropertyChanged("currentweek");
				this.OncurrentweekChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reason", DbType="VarChar(50)")]
	public string reason
	{
		get
		{
			return this._reason;
		}
		set
		{
			if ((this._reason != value))
			{
				this.OnreasonChanging(value);
				this.SendPropertyChanging();
				this._reason = value;
				this.SendPropertyChanged("reason");
				this.OnreasonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_approve", DbType="Int")]
	public System.Nullable<int> approve
	{
		get
		{
			return this._approve;
		}
		set
		{
			if ((this._approve != value))
			{
				this.OnapproveChanging(value);
				this.SendPropertyChanging();
				this._approve = value;
				this.SendPropertyChanged("approve");
				this.OnapproveChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
